const prospectAssetsSchemaCurrent = [
  [
    {
      component: 'Radio',
      optionOne: 'Yes',
      optionTwo: 'No',
      class: 'w-7/24 pt-6',
      name: 'incomePlan',
      model: 'incomePlan',
      label: 'Do you have a written income plan?',
    },
  ],
  [
    {
      component: 'Label',
      label: 'Salary',
      class: 'w-2/12 text-main pt-2 font-semibold',
      model: 'Salary',
      positionLeft: true,
    },
    {
      component: 'Input',
      label: 'OWNER',
      type: 'text',
      name: 'salaryOwner',
      model: 'salaryOwner',
      labelGray: true,
      class: 'w-5/12 pr-5',
    },
    {
      component: 'Input',
      label: 'SPOUSE',
      type: 'text',
      name: 'salarySpouse',
      labelGray: true,
      model: 'salarySpouse',
      class: 'w-5/12 pr-5',
    },
  ],
  [
    {
      component: 'Label',
      label: 'Social Security',
      class: 'w-2/12 text-main font-semibold',
      model: 'socialSecurity',
      positionLeft: true,
    },
    {
      component: 'Input',
      type: 'text',
      name: 'socialSecurityOwner',
      model: 'socialSecurityOwner',
      labelGray: true,
      class: 'w-5/12 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'socialSecuritySpouse',
      labelGray: true,
      model: 'socialSecuritySpouse',
      class: 'w-5/12 pr-5',
    },
  ],
  [
    {
      component: 'Label',
      label: 'Pension',
      class: 'w-2/12 text-main font-semibold',
      model: 'Pension',
      positionLeft: true,
    },
    {
      component: 'Input',
      type: 'text',
      name: 'PensionOwner',
      model: 'PensionOwner',
      labelGray: true,
      class: 'w-5/12 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'PensionSpouse',
      labelGray: true,
      model: 'PensionSpouse',
      class: 'w-5/12 pr-5',
    },
  ],
  [
    {
      component: 'Label',
      label: 'Rental income',
      class: 'w-2/12 text-main font-semibold',
      model: 'Rental',
      positionLeft: true,
    },
    {
      component: 'Input',
      type: 'text',
      name: 'rentalOwner',
      model: 'rentalOwner',
      labelGray: true,
      class: 'w-5/12 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'rentalSpouse',
      labelGray: true,
      model: 'rentalSpouse',
      class: 'w-5/12 pr-5',
    },
  ],
  [
    {
      component: 'Label',
      label: 'RMD’s',
      class: 'w-2/12 text-main font-semibold',
      model: 'rmd',
      positionLeft: true,
    },
    {
      component: 'Input',
      type: 'text',
      name: 'rmdOwner',
      model: 'rmdlOwner',
      labelGray: true,
      class: 'w-5/12 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'rmdSpouse',
      labelGray: true,
      model: 'rmdSpouse',
      class: 'w-5/12 pr-5',
    },
  ],
  [
    {
      component: 'Label',
      label: 'Interest/Dividents',
      class: 'w-2/12 text-main font-semibold',
      model: 'Interest',
      positionLeft: true,
    },
    {
      component: 'Input',
      type: 'text',
      name: 'InterestOwner',
      model: 'InterestOwner',
      labelGray: true,
      class: 'w-5/12 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'InterestSpouse',
      labelGray: true,
      model: 'InterestSpouse',
      class: 'w-5/12 pr-5',
    },
  ],
  [
    {
      component: 'Label',
      label: 'Other',
      class: 'w-2/12 text-main font-semibold',
      model: 'Other',
      positionLeft: true,
    },
    {
      component: 'Input',
      type: 'text',
      name: 'OtherOwner',
      model: 'OtherOwner',
      labelGray: true,
      class: 'w-5/12 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'OtherSpouse',
      labelGray: true,
      model: 'OtherSpouse',
      class: 'w-5/12 pr-5',
    },
  ],
]

const prospectAssetsSchemaLiquid = [
  [
    {
      component: 'Label',
      label: 'Cash/Checking/ Savings/MM',
      class: 'w-4/24 text-main pt-2 font-semibold',
      model: 'SalaryLiquid',
      positionLeft: true,
    },
    {
      component: 'Input',
      label: 'OWNER',
      type: 'text',
      name: 'CashOwner',
      model: 'CashOwner',
      labelGray: true,
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      label: 'SPOUSE',
      type: 'text',
      name: 'CashSpouse',
      labelGray: true,
      model: 'CashSpouse',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      label: 'O/NQ',
      type: 'text',
      name: 'cashOnq',
      model: 'cashOnq',
      labelGray: true,
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      label: 'BALANCE',
      type: 'text',
      name: 'cashbalance',
      labelGray: true,
      model: 'cashbalance',
      class: 'w-5/24 pr-5',
    },
  ],

  [
    {
      component: 'Label',
      label: 'CD’s',
      class: 'w-4/24 text-main pt-2 font-semibold',
      model: 'SalaryLiquid',
      positionLeft: true,
    },
    {
      component: 'Input',
      type: 'text',
      name: 'cdOwner',
      model: 'cdOwner',
      labelGray: true,
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'cdSpouse',
      labelGray: true,
      model: 'cdSpouse',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'cdOnq',
      model: 'cdOnq',
      labelGray: true,
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'cdBalance',
      labelGray: true,
      model: 'cdBalance',
      class: 'w-5/24 pr-5',
    },
  ],
  [
    {
      component: 'Label',
      label: '401k/IRA (if over 59)',
      class: 'w-4/24 text-main pt-2 font-semibold',
      model: 'IRALiquid',
      positionLeft: true,
    },
    {
      component: 'Input',
      type: 'text',
      name: 'IRAOwner',
      model: 'IRAOwner',
      labelGray: true,
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'IRASpouse',
      labelGray: true,
      model: 'IRASpouse',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'IRAOnq',
      model: 'IRAOnq',
      labelGray: true,
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'IRABalance',
      labelGray: true,
      model: 'IRABalance',
      class: 'w-5/24 pr-5',
    },
  ],
  // ************************************************
  [
    {
      component: 'Label',
      label: '401k/IRA',
      class: 'w-4/24 text-main pt-2 font-semibold',
      model: '401kLiquid',
      positionLeft: true,
    },
    {
      component: 'Input',
      type: 'text',
      name: '401kOwner',
      model: '401kOwner',
      labelGray: true,
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: '401kSpouse',
      labelGray: true,
      model: '401kSpouse',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: '401kOnq',
      model: '401kOnq',
      labelGray: true,
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: '401kBalance',
      labelGray: true,
      model: '401kBalance',
      class: 'w-5/24 pr-5',
    },
  ],
  // ************************************************
  [
    {
      component: 'Label',
      label: 'Stocks/Bonds/MF',
      class: 'w-4/24 text-main pt-2 font-semibold',
      model: 'StocksLiquid',
      positionLeft: true,
    },
    {
      component: 'Input',
      type: 'text',
      name: 'StocksOwner',
      model: 'StocksOwner',
      labelGray: true,
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'StocksSpouse',
      labelGray: true,
      model: 'StocksSpouse',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'StocksOnq',
      model: 'StocksOnq',
      labelGray: true,
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'StocksBalance',
      labelGray: true,
      model: 'StocksBalance',
      class: 'w-5/24 pr-5',
    },
  ],
  // ************************************************
  [
    {
      component: 'Label',
      label: 'Cash value life insurance',
      class: 'w-4/24 text-main pt-2 font-semibold',
      model: 'insuranceLiquid',
      positionLeft: true,
    },
    {
      component: 'Input',
      type: 'text',
      name: 'insuranceOwner',
      model: 'insuranceOwner',
      labelGray: true,
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'insuranceSpouse',
      labelGray: true,
      model: 'insuranceSpouse',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'insuranceOnq',
      model: 'insuranceOnq',
      labelGray: true,
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'insuranceBalance',
      labelGray: true,
      model: 'insuranceBalance',
      class: 'w-5/24 pr-5',
    },
  ],
  // ************************************************
  [
    {
      component: 'Label',
      label: 'FA/VA not suject to penalty',
      class: 'w-4/24 text-main pt-2 font-semibold',
      model: 'penaltyLiquid',
      positionLeft: true,
    },
    {
      component: 'Input',
      type: 'text',
      name: 'penaltyOwner',
      model: 'penaltyOwner',
      labelGray: true,
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'penaltySpouse',
      labelGray: true,
      model: 'penaltySpouse',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'penaltyOnq',
      model: 'penaltyOnq',
      labelGray: true,
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'penaltyBalance',
      labelGray: true,
      model: 'penaltyBalance',
      class: 'w-5/24 pr-5',
    },
  ],
  // ************************************************
  [
    {
      component: 'Label',
      label: 'Gift/Inheritance',
      class: 'w-4/24 text-main pt-2 font-semibold',
      model: 'GiftLiquid',
      positionLeft: true,
    },
    {
      component: 'Input',
      type: 'text',
      name: 'GiftOwner',
      model: 'GiftOwner',
      labelGray: true,
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'GiftSpouse',
      labelGray: true,
      model: 'GiftSpouse',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'GiftOnq',
      model: 'GiftOnq',
      labelGray: true,
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'GiftBalance',
      labelGray: true,
      model: 'GiftBalance',
      class: 'w-5/24 pr-5',
    },
  ],
  // ************************************************
  [
    {
      component: 'Label',
      label: 'Lump sum pension',
      class: 'w-4/24 text-main pt-2 font-semibold',
      model: 'LumpLiquid',
      positionLeft: true,
    },
    {
      component: 'Input',
      type: 'text',
      name: 'LumpOwner',
      model: 'LumpOwner',
      labelGray: true,
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'LumpSpouse',
      labelGray: true,
      model: 'LumpSpouse',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'LumptOnq',
      model: 'LumpOnq',
      labelGray: true,
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'LumpBalance',
      labelGray: true,
      model: 'LumpBalance',
      class: 'w-5/24 pr-5',
    },
  ],
  // ************************************************
  [
    {
      component: 'Label',
      label: 'Other liquid assets',
      class: 'w-4/24 text-main pt-2 font-semibold',
      model: 'OtherLiquidAssets',
      positionLeft: true,
    },
    {
      component: 'Input',
      type: 'text',
      name: 'OtherLiquidAssets',
      model: 'OtherLiquidAssets',
      labelGray: true,
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'OtherLiquidAssets',
      labelGray: true,
      model: 'OtherLiquidAssets',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'OtherLiquidAssets',
      model: 'OtherLiquidAssets',
      labelGray: true,
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'OtherLiquidAssets',
      labelGray: true,
      model: 'OtherLiquidAssets',
      class: 'w-5/24 pr-5',
    },
  ],
  // ************************************************
  [
    {
      component: 'Label',
      label: 'Total',
      class: 'w-4/24 text-main pt-2 font-semibold',
      model: 'LiquidTotal',
      positionLeft: true,
    },
    {
      component: 'Input',
      type: 'text',
      name: 'LiquidTotal',
      model: 'LiquidTotal',
      labelGray: true,
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'LiquidTotal',
      labelGray: true,
      model: 'LiquidTotal',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'LiquidTotal',
      model: 'LiquidTotal',
      labelGray: true,
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'LiquidTotal',
      labelGray: true,
      model: 'LiquidTotal',
      class: 'w-5/24 pr-5',
    },
  ],
]

const prospectAssetsSchemaNoLiquid = [
  [
    {
      component: 'Label',
      label: 'Value of home',
      class: 'w-4/24 text-main pt-2 font-semibold',
      model: 'ValueOfHome',
      positionLeft: true,
    },
    {
      component: 'Input',
      label: 'OWNER',
      type: 'text',
      name: 'OwnerValueOfHome',
      model: 'OwnerValueOfHome',
      labelGray: true,
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      label: 'SPOUSE',
      type: 'text',
      name: 'SpouseValueOfHome',
      labelGray: true,
      model: 'SpouseValueOfHome',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      label: 'O/NQ',
      type: 'text',
      name: 'OnqValueOfHome',
      model: 'OnqValueOfHome',
      labelGray: true,
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      label: 'BALANCE',
      type: 'text',
      name: 'balanceValueOfHome',
      labelGray: true,
      model: 'balanceValueOfHome',
      class: 'w-5/24 pr-5',
    },
  ],
  // ************************************************
  [
    {
      component: 'Label',
      label: '401k/IRA (if over 59)',
      class: 'w-4/24 text-main pt-2 font-semibold',
      model: 'IRANoLiquid',
      positionLeft: true,
    },
    {
      component: 'Input',
      type: 'text',
      name: 'IRANoLiquidOwner',
      model: 'IRANoLiquidOwner',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'SpouseIRANoLiquid',
      model: 'SpouseIRANoLiquidOwner',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'OnqIRANoLiquidOwner',
      model: 'OnqIRANoLiquidOwner',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'balanceIRANoLiquidOwner',
      model: 'balanceIRANoLiquidOwner',
      class: 'w-5/24 pr-5',
    },
  ],
  // ************************************************
  [
    {
      component: 'Label',
      label: '401k/IRA',
      class: 'w-4/24 text-main pt-2 font-semibold',
      model: '401NoLiquid',
      positionLeft: true,
    },
    {
      component: 'Input',
      type: 'text',
      name: '401NoLiquidOwner',
      model: '401NoLiquidOwner',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'Spouse401NoLiquid',
      model: 'Spouse401NoLiquidOwner',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'Onq401NoLiquidOwner',
      model: 'Onq401NoLiquidOwner',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'balance401NoLiquidOwner',
      model: 'balance401NoLiquidOwner',
      class: 'w-5/24 pr-5',
    },
  ],
  // ************************************************
  [
    {
      component: 'Label',
      label: 'FA/VA suject to penalty',
      class: 'w-4/24 text-main pt-2 font-semibold',
      model: 'penaltyNoLiquid',
      positionLeft: true,
    },
    {
      component: 'Input',
      type: 'text',
      name: 'penaltyNoLiquidOwner',
      model: 'penaltyNoLiquidOwner',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'SpousepenaltyNoLiquid',
      model: 'SpousepenaltyNoLiquidOwner',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'OnqpenaltyNoLiquidOwner',
      model: 'OnqpenaltyNoLiquidOwner',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'balancepenaltyNoLiquidOwner',
      model: 'balancepenaltyNoLiquidOwner',
      class: 'w-5/24 pr-5',
    },
  ],
  // ************************************************
  [
    {
      component: 'Label',
      label: 'Other',
      class: 'w-4/24 text-main pt-2 font-semibold',
      model: 'OtherNoLiquid',
      positionLeft: true,
    },
    {
      component: 'Input',
      type: 'text',
      name: 'OtherNoLiquidOwner',
      model: 'OtherNoLiquidOwner',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'OtherNoLiquidSpouse',
      model: 'OtherNoLiquidSpouse',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'OthetNoLiquidNQ',
      model: 'OthetNoLiquidNQ',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'OthetNoLiquidBalance',
      model: 'OthetNoLiquidBalance',
      class: 'w-5/24 pr-5',
    },
  ],
  // ************************************************
  [
    {
      component: 'Total',
      label: 'Other',
      class: 'w-4/24 text-main pt-2 font-semibold',
      model: 'TotalNoLiquid',
      positionLeft: true,
    },
    {
      component: 'Input',
      type: 'text',
      name: 'TotalNoLiquidOwner',
      model: 'TotalNoLiquidOwner',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'TotalNoLiquidSpouse',
      model: 'TotalNoLiquidSpouse',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'TotalNoLiquidNQ',
      model: 'TotalNoLiquidNQ',
      class: 'w-5/24 pr-5',
    },
    {
      component: 'Input',
      type: 'text',
      name: 'TotalNoLiquidBalance',
      model: 'TotalNoLiquidBalance',
      class: 'w-5/24 pr-5',
    },
  ],
  // ************************************************
]

export {
  prospectAssetsSchemaCurrent,
  prospectAssetsSchemaLiquid,
  prospectAssetsSchemaNoLiquid,
}
