<template>
  <!-- component -->
  <div class="p-5">
    <div class="mx-4 p-4">
      <div class="flex items-center">
        <div class="flex items-center text-teal-600 relative">
          <div
            class="
              rounded-full
              transition
              duration-500
              ease-in-out
              w-2
              py-3
              border-2 border-teal-600
            "
          />
          <div
            class="
              absolute
              top-0
              -ml-10
              text-center
              mt-16
              w-32
              text-xs
              font-medium
              uppercase
              text-teal-600
            "
          >
            Personal
          </div>
        </div>
        <div
          class="
            flex-auto
            border-t-2
            transition
            duration-500
            ease-in-out
            border-teal-600
          "
        ></div>
        <div class="flex items-center text-white relative">
          <div
            class="
              rounded-full
              transition
              duration-500
              ease-in-out
              h-12
              w-12
              py-3
              border-2
              bg-teal-600
              border-teal-600
            "
          />
          <div
            class="
              absolute
              top-0
              -ml-10
              text-center
              mt-16
              w-32
              text-xs
              font-medium
              uppercase
              text-teal-600
            "
          >
            Account
          </div>
        </div>
        <div
          class="
            flex-auto
            border-t-2
            transition
            duration-500
            ease-in-out
            border-gray-300
          "
        />
        <div class="flex items-center text-gray-500 relative">
          <div
            class="
              rounded-full
              transition
              duration-500
              ease-in-out
              h-12
              w-12
              py-3
              border-2 border-gray-300
            "
          ></div>
          <div
            class="
              absolute
              top-0
              -ml-10
              text-center
              mt-16
              w-32
              text-xs
              font-medium
              uppercase
              text-gray-500
            "
          >
            Message
          </div>
        </div>
        <div
          class="
            flex-auto
            border-t-2
            transition
            duration-500
            ease-in-out
            border-gray-300
          "
        />
        <div class="flex items-center text-gray-500 relative">
          <div
            class="
              rounded-full
              transition
              duration-500
              ease-in-out
              h-12
              w-12
              py-3
              border-2 border-gray-300
            "
          />
          <div
            class="
              absolute
              top-0
              -ml-10
              text-center
              mt-16
              w-32
              text-xs
              font-medium
              uppercase
              text-gray-500
            "
          >
            Confirm
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
export default {
  name: 'NewProspectSteps',
}
</script>
