export const initialAssetsInformation = {
  income: {
    income_plan: true,
    member: {
      salary: '',
      social_security: '',
      pension: '',
      rental_income: '',
      rmds: '',
      interest_dividends: '',
      other: '',
    },
    spouse: {
      salary: '',
      social_security: '',
      pension: '',
      rental_income: '',
      rmds: '',
      interest_dividends: '',
      other: '',
    },
  },
  liquid_assets: {
    member: {
      gift_inheritance: '',
      first_401k_ira_59: '',
      cash_value_life_insurance: '',
      total: '',
      second_401k_ira: '',
      cash_checking_savings_mm: '',
      stocks_bonds_mf: '',
      first_401k_ira: '',
      other_liquid_assets: '',
      cds: '',
      lump_sum_pension: '',
      fa_va_not_subject_to_penalty: '',
    },
    spouse: {
      gift_inheritance: '',
      first_401k_ira_59: '',
      cash_value_life_insurance: '',
      total: '',
      second_401k_ira: '',
      cash_checking_savings_mm: '',
      stocks_bonds_mf: '',
      first_401k_ira: '',
      other_liquid_assets: '',
      cds: '',
      lump_sum_pension: '',
      fa_va_not_subject_to_penalty: '',
    },
    o_nq: {
      gift_inheritance: '',
      first_401k_ira_59: '',
      cash_value_life_insurance: '',
      total: '',
      second_401k_ira: '',
      cash_checking_savings_mm: '',
      stocks_bonds_mf: '',
      first_401k_ira: '',
      other_liquid_assets: '',
      cds: '',
      lump_sum_pension: '',
      fa_va_not_subject_to_penalty: '',
    },
    balance: {
      gift_inheritance: '',
      first_401k_ira_59: '',
      cash_value_life_insurance: '',
      total: '',
      second_401k_ira: '',
      cash_checking_savings_mm: '',
      stocks_bonds_mf: '',
      first_401k_ira: '',
      other_liquid_assets: '',
      cds: '',
      lump_sum_pension: '',
      fa_va_not_subject_to_penalty: '',
    },
  },
  non_liquid_assets: {
    member: {
      total: '',
      other: '',
      fa_va_subject_to_penalty: '',
      second_401k_ira: '',
      first_401k_ira: '',
      first_401k_ira_59: '',
      value_of_home: '',
    },
    spouse: {
      total: '',
      other: '',
      fa_va_subject_to_penalty: '',
      second_401k_ira: '',
      first_401k_ira: '',
      first_401k_ira_59: '',
      value_of_home: '',
    },
    o_nq: {
      total: '',
      other: '',
      fa_va_subject_to_penalty: '',
      second_401k_ira: '',
      first_401k_ira: '',
      first_401k_ira_59: '',
      value_of_home: '',
    },
    balance: {
      total: '',
      other: '',
      fa_va_subject_to_penalty: '',
      second_401k_ira: '',
      first_401k_ira: '',
      first_401k_ira_59: '',
      value_of_home: '',
    },
  },
  member_id: '',
}
