export const initialBasicInformation = {
  retired: false,
  married: true,
  name: '',
  birthday: '',
  retirement_date: '',
  email: '',
  address: '',
  city: '',
  state: '',
  zip: '',
  phone: '',
  spouse: {
    name: '',
    email: '',
    birthday: '',
    retired: false,
    retirement_date: '',
    phone: '',
    employment_history: [
      {
        company_name: '',
        occupation: '',
        years: '',
      },
    ],
  },
  house: {
    type: 'own',
    market_value: null,
    monthly_payments: null,
    remaining_mortgage_amount: null,
    monthly_payment: null,
    total_monthly_expenses: null,
  },
  employment_history: [
    {
      company_name: '',
      occupation: '',
      years: '',
    },
  ],
  other: {
    risk: 'conservative',
    questions: '',
    retirement: '',
    retirement_money: '',
    work_with_advisor: true,
  },
}
